SELECT b.AUTHOR_ID,	a.AUTHOR_NAME,	b.CATEGORY, (SUM(bs.SALES * b.PRICE))	AS TOTAL_SALES
FROM BOOK AS b
JOIN AUTHOR AS a ON a.AUTHOR_ID = b.AUTHOR_ID
JOIN BOOK_SALES AS bs ON bs.BOOK_ID = b.BOOK_ID
WHERE bs.SALES_DATE LIKE '2022-01%'
GROUP BY b.AUTHOR_ID, b.CATEGORY
ORDER BY b.AUTHOR_ID, b.CATEGORY DESC
;

