-- PARENT_ID로 groupBy해서, 부모 별 자식수 세기
-- left join으로 자식수
-- 원래 id출력, 없으면 0
-- COALESCE(null일수도 있는 값, 대체값)


SELECT E1.ID, COALESCE(E2.CHILD_COUNT , 0) AS CHILD_COUNT
FROM ECOLI_DATA AS E1
LEFT JOIN(
    SELECT PARENT_ID , COUNT(*) AS CHILD_COUNT
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NOT NULL
    GROUP BY PARENT_ID
    
) AS E2
ON E1.ID = E2.PARENT_ID
ORDER BY E1.ID;

