-- PARENT_ID로 groupBy하기
-- 원래 id출력, 없으면 0

SELECT E1.ID, COALESCE(E2.CNT, 0) AS CHILD_COUNT
FROM ECOLI_DATA AS E1
LEFT JOIN (
    SELECT PARENT_ID,COUNT(*) AS CNT
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NOT NULL
    GROUP BY PARENT_ID
) AS E2
ON E1.ID = E2.PARENT_ID
ORDER BY E1.ID;
    
    
    