-- 음슥종류별로 즐겨찾기 가장많은 식당
SELECT I1.FOOD_TYPE,	I1.REST_ID,	I1.REST_NAME,	I2.FAVORITES
FROM REST_INFO AS I1
RIGHT JOIN(
    SELECT FOOD_TYPE, MAX(FAVORITES) AS FAVORITES
    FROM REST_INFO
    GROUP BY FOOD_TYPE
    
) AS I2
ON I1.FOOD_TYPE = I2.FOOD_TYPE AND I1.FAVORITES = I2.FAVORITES
ORDER BY I1.FOOD_TYPE DESC;

