-- 완료된 중고거래의 총금액이 70이상인 사람
-- 일단 완료된 중고거래를 writerId별로 묶어서 총합 구하기

SELECT B.WRITER_ID AS USER_ID, U.NICKNAME, SUM(B.PRICE) AS TOT_PRICE
FROM USED_GOODS_BOARD AS B

JOIN USED_GOODS_USER AS U
ON B.WRITER_ID = U.USER_ID

WHERE STATUS = 'DONE'

GROUP BY WRITER_ID
HAVING TOT_PRICE >= 700000

ORDER BY TOT_PRICE
;