-- HAVING COUNT(*) > 4는 “월별로 5건 이상 대여가 있었던 CAR_ID”만 필터링합니다.
-- 그런데 문제는 “3개월(8~10월) 동안 총 대여 횟수가 5회 이상인 CAR_ID만을 대상”으로 월별 집계를 해야 하는 거예요.

SELECT MONTH(t1.START_DATE) AS MONTH, t1.CAR_ID, COUNT(*) AS RECORDS

FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS t1



JOIN (
    SELECT	CAR_ID,  COUNT(*) AS RECORDS
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE >= '2022-08-01' 
        AND START_DATE <= '2022-10-31'
    GROUP BY CAR_ID
    HAVING COUNT(*) > 4
    ) AS t2
    
ON t1.CAR_ID = t2.CAR_ID

WHERE START_DATE >= '2022-08-01' 
        AND START_DATE <= '2022-10-31'
        
GROUP BY t2.CAR_ID, MONTH(t1.START_DATE)

ORDER BY MONTH(t1.START_DATE), t1.CAR_ID DESC

;