-- 카테고리별로 가격이 제일 비싼 식품의 분류 가격 이름
-- 식품분류가 과자국김치식용유인것만 선택,
-- rank() 1인것만 집계

SELECT T1.CATEGORY,	T2.MAX_PRICE,	T1.PRODUCT_NAME
FROM FOOD_PRODUCT AS T1
RIGHT JOIN (
    SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
    GROUP BY CATEGORY
    ) AS T2
ON T1.CATEGORY = T2.CATEGORY AND T1.PRICE = T2.MAX_PRICE
ORDER BY T2.MAX_PRICE DESC
;